version: "2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: haddock
      MYSQL_USER: captain
      MYSQL_PASSWORD: tintin
    volumes:
      - ./storage/mysql:/var/lib/mysql
  mysql_test:
    image: mysql:5.7
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: haddock_test
      MYSQL_USER: captain
      MYSQL_PASSWORD: tintin
    volumes:
      - ./storage/mysql:/var/lib/mysql_test
